version: "2"
services:
  server:
    image: mern_srv:latest
    ports:
     - "4000:4000"
    links:
     - mongodb
  mongodb:
    image: mongo
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: events